language: python
#python:
#  - "3.6"
install:
  - pip install tox
  - pip install -r requirements-test.txt
script: tox -e $TOX_ENV
matrix:
  include:
    - python: 2.7
      env: TOX_ENV=py27-django-111
    - python: 2.7
      env: TOX_ENV=py27-django-18
    - python: 3.4
      env: TOX_ENV=py34-django-111
    - python: 3.4
      env: TOX_ENV=py34-django-18
    - python: 3.5
      env: TOX_ENV=py35-django-111
    - python: 3.5
      env: TOX_ENV=py35-django-18
    - python: 3.6
      env: TOX_ENV=py36-django-111
    - python: 3.6
      env: TOX_ENV=py36-django-18
    - python: 3.4
      env: TOX_ENV=py34-django-2
    - python: 3.5
      env: TOX_ENV=py35-django-2
    - python: 3.6
      env: TOX_ENV=py36-django-2
    - python: 3.6
      env: TOX_ENV=py36-django-3
#env:
#  - TOX_ENV=py36-django-18
#  - TOX_ENV=py35-django-18
#  - TOX_ENV=py34-django-18
#  - TOX_ENV=py27-django-18
#  - TOX_ENV=py36-django-19
#  - TOX_ENV=py35-django-19
#  - TOX_ENV=py34-django-19
#  - TOX_ENV=py27-django-19
#  - TOX_ENV=py36-django-110
#  - TOX_ENV=py35-django-110
#  - TOX_ENV=py34-django-110
#  - TOX_ENV=py27-django-110
#  - TOX_ENV=py36-django-111
#  - TOX_ENV=py35-django-111
#  - TOX_ENV=py34-django-111
#  - TOX_ENV=py27-django-111
